main: main.ml XList/XList.ml XString/XString.ml XFileIO/XFileIO.ml XChar/XChar.ml
	ocamlopt -o main -I XList -I XString -I XFileIO -I  XChar XList/XList.ml XString/XString.ml XFileIO/XFileIO.ml XChar/XChar.ml main.ml
